apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redemption-platform
  namespace: argocd
  labels:
    app.kubernetes.io/name: redemption
    app.kubernetes.io/component: gitops
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: redemption-platform
    environment: production
spec:
  project: default
  source:
    repoURL: https://github.com/myintheinkyaw/redemption-cloud-engineer-assessment.git
    targetRevision: main
    path: kubernetes/apps/the-redemption

  destination:
    server: https://kubernetes.default.svc
    namespace: redemption

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
